name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        flutter-version: [ 2.0.3 ]
        target: [ 'apk --release', 'ios --release --no-codesign' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ matrix.flutter-version }}
      - name: Install dependencies
        run: flutter pub get
      - name: Check formatting
        run: flutter format --set-exit-if-changed .
      - name: Analyze code
        run: flutter analyze
      - name: Run tests
        run: flutter test
      - name: build android & ios
        run: flutter build ${{ matrix.target }}
